### ISSUE TITLE
WHY NO WORK!!! I NEED THIS

### ISSUE THREAD

**Issue by a-ctor** [dauthleikr/Llama#1]
```
int Test(cstr[][][][][][][][][][] a)
{
	a[0][1][2][3][4][5][6][7][8][9] = 4;
}

cstr[][][][][][][][][][] a;
Test(a);
```

I HAVE FAMILIY TO SUSTAN!!!!!

```
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Llama.Compiler.PreferredRegister.op_Implicit(Register register) in S:\GitHub\ninowsshittycompiler\Llama.Compiler\PreferredRegister.cs:line 24
   at Llama.Compiler.ExpressionCompilers.ArrayAccessCompiler.Compile(ArrayAccessExpression expression, PreferredRegister target, CodeGen codeGen, StorageManager storageManager, IScopeContext scope, IAddressFixer addressFixer, ICompilationContext context) in S:\GitHub\ninowsshittycompiler\Llama.Compiler\ExpressionCompilers\ArrayAccessCompiler.cs:line 20
   at Llama.Compiler.CompilationContext.CompileExpression[T](T expression, CodeGen codeGen, StorageManager storageManager, PreferredRegister target, IScopeContext scope) in S:\GitHub\ninowsshittycompiler\Llama.Compiler\CompilationContext.cs:line 37
   at Llama.Compiler.ExpressionCompilers.GenericExpressionCompiler.Compile(IExpression expression, PreferredRegister target, CodeGen codeGen, StorageManager storageManager, IScopeContext scope, IAddressFixer addressFixer, ICompilationContext context) in S:\GitHub\ninowsshittycompiler\Llama.Compiler\ExpressionCompilers\GenericExpressionCompiler.cs:line 22
   at Llama.Compiler.CompilationContext.CompileExpression[T](T expression, CodeGen codeGen, StorageManager storageManager, PreferredRegister target, IScopeContext scope) in S:\GitHub\ninowsshittycompiler\Llama.Compiler\CompilationContext.cs:line 37
   at Llama.Compiler.ExpressionCompilers.ArrayAccessCompiler.Compile(ArrayAccessExpression expression, PreferredRegister target, CodeGen codeGen, StorageManager storageManager, IScopeContext scope, IAddressFixer addressFixer, ICompilationContext context) in S:\GitHub\ninowsshittycompiler\Llama.Compiler\ExpressionCompilers\ArrayAccessCompiler.cs:line 20
   at Llama.Compiler.CompilationContext.CompileExpression[T](T expression, CodeGen codeGen, StorageManager storageManager, PreferredRegister target, IScopeContext scope) in S:\GitHub\ninowsshittycompiler\Llama.Compiler\CompilationContext.cs:line 37
   at Llama.Compiler.ExpressionCompilers.GenericExpressionCompiler.Compile(IExpression expression, PreferredRegister target, CodeGen codeGen, StorageManager storageManager, IScopeContext scope, IAddressFixer addressFixer, ICompilationContext context) in S:\GitHub\ninowsshittycompiler\Llama.Compiler\ExpressionCompilers\GenericExpressionCompiler.cs:line 22
   at Llama.Compiler.CompilationContext.CompileExpression[T](T expression, CodeGen codeGen, StorageManager storageManager, PreferredRegister target, IScopeContext scope) in S:\GitHub\ninowsshittycompiler\Llama.Compiler\CompilationContext.cs:line 37
   at Llama.Compiler.ExpressionCompilers.ArrayAccessCompiler.Compile(ArrayAccessExpression expression, PreferredRegister target, CodeGen codeGen, StorageManager storageManager, IScopeContext scope, IAddressFixer addressFixer, ICompilationContext context) in S:\GitHub\ninowsshittycompiler\Llama.Compiler\ExpressionCompilers\ArrayAccessCompiler.cs:line 20
   at Llama.Compiler.CompilationContext.CompileExpression[T](T expression, CodeGen codeGen, StorageManager storageManager, PreferredRegister target, IScopeContext scope) in S:\GitHub\ninowsshittycompiler\Llama.Compiler\CompilationContext.cs:line 37
   at Llama.Compiler.ExpressionCompilers.GenericExpressionCompiler.Compile(IExpression expression, PreferredRegister target, CodeGen codeGen, StorageManager storageManager, IScopeContext scope, IAddressFixer addressFixer, ICompilationContext context) in S:\GitHub\ninowsshittycompiler\Llama.Compiler\ExpressionCompilers\GenericExpressionCompiler.cs:line 22
   at Llama.Compiler.CompilationContext.CompileExpression[T](T expression, CodeGen codeGen, StorageManager storageManager, PreferredRegister target, IScopeContext scope) in S:\GitHub\ninowsshittycompiler\Llama.Compiler\CompilationContext.cs:line 37
   at Llama.Compiler.ExpressionCompilers.ArrayAccessCompiler.Compile(ArrayAccessExpression expression, PreferredRegister target, CodeGen codeGen, StorageManager storageManager, IScopeContext scope, IAddressFixer addressFixer, ICompilationContext context) in S:\GitHub\ninowsshittycompiler\Llama.Compiler\ExpressionCompilers\ArrayAccessCompiler.cs:line 20
   at Llama.Compiler.CompilationContext.CompileExpression[T](T expression, CodeGen codeGen, StorageManager storageManager, PreferredRegister target, IScopeContext scope) in S:\GitHub\ninowsshittycompiler\Llama.Compiler\CompilationContext.cs:line 37
   at Llama.Compiler.ExpressionCompilers.GenericExpressionCompiler.Compile(IExpression expression, PreferredRegister target, CodeGen codeGen, StorageManager storageManager, IScopeContext scope, IAddressFixer addressFixer, ICompilationContext context) in S:\GitHub\ninowsshittycompiler\Llama.Compiler\ExpressionCompilers\GenericExpressionCompiler.cs:line 22
   at Llama.Compiler.CompilationContext.CompileExpression[T](T expression, CodeGen codeGen, StorageManager storageManager, PreferredRegister target, IScopeContext scope) in S:\GitHub\ninowsshittycompiler\Llama.Compiler\CompilationContext.cs:line 37
   at Llama.Compiler.ExpressionCompilers.ArrayAccessCompiler.Compile(ArrayAccessExpression expression, PreferredRegister target, CodeGen codeGen, StorageManager storageManager, IScopeContext scope, IAddressFixer addressFixer, ICompilationContext context) in S:\GitHub\ninowsshittycompiler\Llama.Compiler\ExpressionCompilers\ArrayAccessCompiler.cs:line 20
   at Llama.Compiler.CompilationContext.CompileExpression[T](T expression, CodeGen codeGen, StorageManager storageManager, PreferredRegister target, IScopeContext scope) in S:\GitHub\ninowsshittycompiler\Llama.Compiler\CompilationContext.cs:line 37
   at Llama.Compiler.ExpressionCompilers.GenericExpressionCompiler.Compile(IExpression expression, PreferredRegister target, CodeGen codeGen, StorageManager storageManager, IScopeContext scope, IAddressFixer addressFixer, ICompilationContext context) in S:\GitHub\ninowsshittycompiler\Llama.Compiler\ExpressionCompilers\GenericExpressionCompiler.cs:line 22
   at Llama.Compiler.CompilationContext.CompileExpression[T](T expression, CodeGen codeGen, StorageManager storageManager, PreferredRegister target, IScopeContext scope) in S:\GitHub\ninowsshittycompiler\Llama.Compiler\CompilationContext.cs:line 37
   at Llama.Compiler.ExpressionCompilers.ArrayAccessCompiler.Compile(ArrayAccessExpression expression, PreferredRegister target, CodeGen codeGen, StorageManager storageManager, IScopeContext scope, IAddressFixer addressFixer, ICompilationContext context) in S:\GitHub\ninowsshittycompiler\Llama.Compiler\ExpressionCompilers\ArrayAccessCompiler.cs:line 20
   at Llama.Compiler.CompilationContext.CompileExpression[T](T expression, CodeGen codeGen, StorageManager storageManager, PreferredRegister target, IScopeContext scope) in S:\GitHub\ninowsshittycompiler\Llama.Compiler\CompilationContext.cs:line 37
   at Llama.Compiler.ExpressionCompilers.GenericExpressionCompiler.Compile(IExpression expression, PreferredRegister target, CodeGen codeGen, StorageManager storageManager, IScopeContext scope, IAddressFixer addressFixer, ICompilationContext context) in S:\GitHub\ninowsshittycompiler\Llama.Compiler\ExpressionCompilers\GenericExpressionCompiler.cs:line 22
   at Llama.Compiler.CompilationContext.CompileExpression[T](T expression, CodeGen codeGen, StorageManager storageManager, PreferredRegister target, IScopeContext scope) in S:\GitHub\ninowsshittycompiler\Llama.Compiler\CompilationContext.cs:line 37
   at Llama.Compiler.ExpressionCompilers.ArrayAccessCompiler.Compile(ArrayAccessExpression expression, PreferredRegister target, CodeGen codeGen, StorageManager storageManager, IScopeContext scope, IAddressFixer addressFixer, ICompilationContext context) in S:\GitHub\ninowsshittycompiler\Llama.Compiler\ExpressionCompilers\ArrayAccessCompiler.cs:line 20
   at Llama.Compiler.CompilationContext.CompileExpression[T](T expression, CodeGen codeGen, StorageManager storageManager, PreferredRegister target, IScopeContext scope) in S:\GitHub\ninowsshittycompiler\Llama.Compiler\CompilationContext.cs:line 37
   at Llama.Compiler.ExpressionCompilers.GenericExpressionCompiler.Compile(IExpression expression, PreferredRegister target, CodeGen codeGen, StorageManager storageManager, IScopeContext scope, IAddressFixer addressFixer, ICompilationContext context) in S:\GitHub\ninowsshittycompiler\Llama.Compiler\ExpressionCompilers\GenericExpressionCompiler.cs:line 22
   at Llama.Compiler.CompilationContext.CompileExpression[T](T expression, CodeGen codeGen, StorageManager storageManager, PreferredRegister target, IScopeContext scope) in S:\GitHub\ninowsshittycompiler\Llama.Compiler\CompilationContext.cs:line 37
   at Llama.Compiler.ExpressionCompilers.BinaryOperationCompiler.PrepareBinaryExpression(IExpression first, IExpression second, PreferredRegister preferredFirst, CodeGen codeGen, StorageManager storageManager, IScopeContext scope, IAddressFixer addressFixer, ICompilationContext context, Boolean shouldDereferenceForImplicitCast) in S:\GitHub\ninowsshittycompiler\Llama.Compiler\ExpressionCompilers\BinaryOperationCompiler.cs:line 450
   at Llama.Compiler.ExpressionCompilers.BinaryOperationCompiler.CompileAssign(IExpression left, IExpression right, PreferredRegister target, CodeGen codeGen, StorageManager storageManager, IScopeContext scope, IAddressFixer addressFixer, ICompilationContext context) in S:\GitHub\ninowsshittycompiler\Llama.Compiler\ExpressionCompilers\BinaryOperationCompiler.cs:line 358
   at Llama.Compiler.ExpressionCompilers.BinaryOperationCompiler.Compile(BinaryOperatorExpression expression, PreferredRegister target, CodeGen codeGen, StorageManager storageManager, IScopeContext scope, IAddressFixer addressFixer, ICompilationContext context) in S:\GitHub\ninowsshittycompiler\Llama.Compiler\ExpressionCompilers\BinaryOperationCompiler.cs:line 59
   at Llama.Compiler.CompilationContext.CompileExpression[T](T expression, CodeGen codeGen, StorageManager storageManager, PreferredRegister target, IScopeContext scope) in S:\GitHub\ninowsshittycompiler\Llama.Compiler\CompilationContext.cs:line 37
   at Llama.Compiler.ExpressionCompilers.GenericExpressionCompiler.Compile(IExpression expression, PreferredRegister target, CodeGen codeGen, StorageManager storageManager, IScopeContext scope, IAddressFixer addressFixer, ICompilationContext context) in S:\GitHub\ninowsshittycompiler\Llama.Compiler\ExpressionCompilers\GenericExpressionCompiler.cs:line 28
   at Llama.Compiler.CompilationContext.CompileExpression[T](T expression, CodeGen codeGen, StorageManager storageManager, PreferredRegister target, IScopeContext scope) in S:\GitHub\ninowsshittycompiler\Llama.Compiler\CompilationContext.cs:line 37
   at Llama.Compiler.StatementCompilers.CodeBlockCompiler.Compile(CodeBlock statement, CodeGen codeGen, StorageManager storageManager, IScopeContext scope, IAddressFixer addressFixer, ICompilationContext context) in S:\GitHub\ninowsshittycompiler\Llama.Compiler\StatementCompilers\CodeBlockCompiler.cs:line 42
   at Llama.Compiler.CompilationContext.CompileStatement[T](T statement, CodeGen codeGen, StorageManager storageManager, IScopeContext scope) in S:\GitHub\ninowsshittycompiler\Llama.Compiler\CompilationContext.cs:line 24
   at Llama.Compiler.Compiler.AddFunction(FunctionImplementation function, IEnumerable`1 imports, IEnumerable`1 declarations) in S:\GitHub\ninowsshittycompiler\Llama.Compiler\Compiler.cs:line 39
   at Llama.Compiler.Cli.Program.Main(String[] args) in S:\GitHub\ninowsshittycompiler\Llama.Compiler.Cli\Program.cs:line 40
The terminal process terminated with exit code: 1
```

**Comment by dauthleikr** [comment]
Fixed f2610eb12e641cf2078b288a557db8264b2a1724 
good luck sustaining "FAMILIY" comrade o7
